# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d6afbd38ab805626da8af30b55dedc79d6de31c2a4647f3ca0d88ba4a39ba262a8c552e7193ca27ac0d268f0f59aa37f482e4e04ab95b538a208f289dd50b56

test:
  secret_key_base: d4ea931c657283535b84709e60c6c532516d2f404ebe94ea33b3a800b60d5478adcc10ca4bb918a1e206700b34427a2c1d2901a26666e7f97084e74390b40ca6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
